name       : python-arpeggio
version    : 2.0.0
release    : 7
source     :
    - https://files.pythonhosted.org/packages/source/A/Arpeggio/Arpeggio-2.0.0.tar.gz : d6b03839019bb8a68785f9292ee6a36b1954eb84b925b84a6b8a5e1e26d3ed3d
homepage   : https://github.com/textX/Arpeggio
license    : MIT
component  : programming.python
summary    : Parser interpreter based on PEG grammars written in Python
description: |
    Arpeggio is a recursive descent parser with memoization based on PEG grammars (aka Packrat parser)
builddeps  :
    - pytest-runner
    - python-wheel
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
